from __future__ import annotations
from typing import Any, Protocol
class HarnessAdapter(Protocol):
    key: str
    def validate_native_payload(self, payload: dict[str, Any]) -> None: ...
    def build_command(self, definition, request, profile) -> Any: ...
    def declare_runtime_sources(self, definition, request, profile): ...
    def decode_observation(self, value): ...
    def observe(self, handle): ...
    def finish(self, handle): ...
