import { useEffect, useMemo, useState, type FormEvent } from "react";
import { api, type SkillInventory } from "../../api/client";
import { useQuery } from "../../api/query";
import { navigate } from "../../app/router";

const errorText = (value: unknown) => String(value instanceof Error ? value.message : value).slice(0, 300);

export function QuickLaunch({ initialWorkId }: { initialWorkId?: string }) {
  const works = useQuery(api.works, []); const discovery = useQuery(api.quickLaunchDiscovery, []); const repositories = useQuery(api.repositories, []);
  const [providerId, setProviderId] = useState(""); const provider = discovery.data?.providers.find((item) => item.id === providerId) ?? discovery.data?.providers[0];
  const [workId, setWorkId] = useState(initialWorkId || "__new__"); const [objective, setObjective] = useState(""); const [responsibility, setResponsibility] = useState(""); const [values, setValues] = useState<Record<string, string>>({}); const [selected, setSelected] = useState<Record<string, string>>({}); const [choices, setChoices] = useState<Record<string, any[]>>({}); const [mode, setMode] = useState("fresh"); const [continuations, setContinuations] = useState<any[]>([]); const [sourceExecution, setSourceExecution] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState("");
  const [inventory, setInventory] = useState<SkillInventory>();
  const groups = useMemo(() => { const map = new Map<string, any[]>(); for (const selector of provider?.selectors ?? []) { const list = map.get(selector.contract_id) ?? []; list.push(selector); map.set(selector.contract_id, list); } return [...map.entries()].filter(([contractId]) => (provider?.requirements ?? []).some((requirement) => requirement.contract_id === contractId)); }, [provider]);
  const setValue = (key: string, value: string) => setValues((old) => ({ ...old, [key]: value }));
  useEffect(() => { if (!providerId && provider) setProviderId(provider.id); }, [providerId, provider]);
  useEffect(() => { const defaults: Record<string, string> = {}; for (const [contractId, candidates] of groups) if (candidates.length === 1) defaults[contractId] = candidates[0].id; setSelected(defaults); setValues({}); setChoices({}); setSourceExecution(""); setInventory(undefined); }, [providerId, groups]);
  const chosenSelectors = useMemo(() => groups.map(([contractId, candidates]) => candidates.find((candidate) => candidate.id === selected[contractId])).filter(Boolean), [groups, selected]);
  useEffect(() => { let active = true; void Promise.all(chosenSelectors.map(async (selector) => [selector.id, await api.choices(selector.id)] as const)).then((entries) => { if (active) setChoices(Object.fromEntries(entries)); }).catch((cause) => { if (active) setError(errorText(cause)); }); return () => { active = false; }; }, [chosenSelectors]);
  useEffect(() => { if (mode === "continue" && workId !== "__new__") void api.continuations(workId, provider?.id).then((result) => setContinuations(result.candidates)).catch((cause) => setError(errorText(cause))); }, [mode, workId, provider?.id]);
  // after a Profile is chosen, show its Effective Skill Inventory (read-only)
  const profileSelector = chosenSelectors.find((selector) => selector.contract_id === "agent-box.profile@1");
  const selectedProfile = profileSelector ? values[`${profileSelector.id}:profile_id`] : "";
  useEffect(() => { if (!provider || !selectedProfile) { setInventory(undefined); return; } let active = true; void api.skillInventory(provider.id, selectedProfile).then((value) => { if (active) setInventory(value); }).catch(() => { if (active) setInventory(undefined); }); return () => { active = false; }; }, [provider?.id, selectedProfile]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (pending || !provider || chosenSelectors.length !== groups.length) return; setPending(true); setError(""); try { const inputs = chosenSelectors.map((selector) => ({ selector_id: selector.id, parameters: Object.fromEntries(selector.fields.map((field) => [field.key, values[`${selector.id}:${field.key}`] ?? field.default])) })); const result = await api.quickLaunch({ work_id: workId === "__new__" ? undefined : workId, objective, responsibility, provider_id: provider.id, inputs, continuation_source_execution_id: mode === "continue" ? sourceExecution : undefined }); navigate(`/executions/${result.execution.id}/binding`); } catch (cause) { setError(errorText(cause)); setPending(false); } };
  return <div className="wb-page"><header className="wb-title"><p>QUICK LAUNCH / GOVERNED</p><h1>Quick Launch</h1><span>Choose a provider, an explicit selector for each required contract, and exact Binding inputs. Ordinary Executions never carry SkillRefs — installed and project Skills are read from the Profile and Workspace.</span></header><form className="wb-form" onSubmit={submit} aria-busy={pending}><label>Work<select value={workId} onChange={(event) => setWorkId(event.target.value)}><option value="__new__">Create new Work</option>{works.data?.works.filter((work) => work.lifecycle === "open").map((work) => <option key={work.id} value={work.id}>{work.objective}</option>)}</select></label>{workId === "__new__" && <label>Work objective<textarea value={objective} onChange={(event) => setObjective(event.target.value)} required /></label>}<label>Execution responsibility<textarea value={responsibility} onChange={(event) => setResponsibility(event.target.value)} required /></label><label>Execution provider<select value={provider?.id ?? ""} onChange={(event) => setProviderId(event.target.value)}>{discovery.data?.providers.map((item) => <option key={item.id} value={item.id}>{item.display_name} · {item.id}</option>)}</select></label>{groups.map(([contractId, candidates]) => <fieldset key={contractId}><legend>Contract: {contractId}</legend>{candidates.length > 1 && <label>Selector<select value={selected[contractId] ?? ""} onChange={(event) => setSelected((old) => ({ ...old, [contractId]: event.target.value }))} required><option value="">Choose selector</option>{candidates.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.title} · {candidate.plugin_id ?? "installed plugin"}</option>)}</select></label>}{candidates.length === 1 && <p className="wb-notice">Selected selector: {candidates[0].title} · {candidates[0].id}</p>}{chosenSelectors.filter((selector) => selector.contract_id === contractId).map((selector) => selector.fields.map((field) => { const key = `${selector.id}:${field.key}`; const fieldChoices = choices[selector.id] ?? (field.key === "repository_id" ? repositories.data?.repositories.map((item) => ({ value: item.id, label: item.name })) : []); return <label key={key}>{field.label}{fieldChoices.length ? <select value={values[key] ?? field.default} required={field.required} onChange={(event) => setValue(key, event.target.value)}><option value="">Choose</option>{fieldChoices.map((choice) => <option key={choice.value ?? choice.id} value={choice.value ?? choice.id}>{choice.label ?? choice.name}</option>)}</select> : <input value={values[key] ?? field.default} required={field.required} onChange={(event) => setValue(key, event.target.value)} />}</label>; }))}</fieldset>)}
    {inventory && <section className="wb-panel"><h3>Effective Skill Inventory · {selectedProfile}</h3><p className="wb-notice">Read-only: installed (central), profile-local and project Skills available to the Harness through native discovery.</p>{inventory.entries.length === 0 && <p className="wb-empty">No skills.</p>}{inventory.entries.map((entry) => <p key={`${entry.source_kind}:${entry.identity}`}><strong>{entry.identity}</strong> · {entry.source_kind} · {entry.claim} · {entry.state}{entry.native_target && <> → <code>{entry.native_target}</code></>}{entry.project_path && <> · <code>{entry.project_path}</code></>}{entry.detail && <><br /><span className="wb-empty">{entry.detail}</span></>}</p>)}</section>}
    <label>Session mode<select value={mode} onChange={(event) => setMode(event.target.value)}><option value="fresh">Fresh session</option><option value="continue">Continue previous session</option></select></label>{mode === "continue" && <label>Previous Execution<select value={sourceExecution} onChange={(event) => setSourceExecution(event.target.value)} required><option value="">Choose</option>{continuations.map((item) => <option key={`${item.source_execution_id}:${item.route_id}`} value={item.source_execution_id}>{item.source_execution_id} · {item.compatibility}</option>)}</select></label>}{error && <p className="wb-error">{error}</p>}<p className="wb-notice">Selector identity, bounded schema, and compatibility come from the installed Catalog. Review remains the authority before Freeze and Dispatch. Skills are never silently installed or upgraded from Quick Launch.</p><button className="primary" disabled={pending || !provider || chosenSelectors.length !== groups.length || !responsibility.trim() || (workId === "__new__" && !objective.trim())}>{pending ? "Preparing…" : "Prepare Binding"}</button></form></div>;
}