// The session surface's shared reactive state, decomposed (this file stays
// the stable import path with the unchanged public surface):
// - atoms             - the atom bank + scoped-persistence setters + composer selection
// - navigation-memory - remembered last session/route + sync owner knowledge
// - default-workspace - configured default project dir + boot workspace seeding
// - identity          - pins, lineage aliases, composer scope keys
// - list-merge        - sidebar session list merge/carry/refresh
// - owner-hints       - persisted exact owner routes

export {
  $activeSessionId,
  $activeSessionStoredIdRotation,
  $availablePersonalities,
  $awaitingResponse,
  $busy,
  $connection,
  $contextSuggestions,
  $cronSessions,
  $currentBranch,
  $currentCwd,
  $currentFastMode,
  $currentModel,
  $currentModelSource,
  $currentPersonality,
  $currentProvider,
  $currentReasoningEffort,
  $currentServiceTier,
  $currentUsage,
  $defaultReasoningEffort,
  $freshDraftReady,
  $gatewayState,
  $introPersonality,
  $introSeed,
  $lastReadAtBySessionId,
  $lastVisibleMessageIsUser,
  $messages,
  $messagesEmpty,
  $messagingPlatformTotals,
  $messagingSessions,
  $messagingTruncated,
  $modelPickerOpen,
  $newChatWorkspaceTarget,
  $newChatWorkspaceTargetGeneration,
  $resumeExhaustedSessionId,
  $resumeFailedSessionId,
  $selectedStoredSessionId,
  $sessionPickerOpen,
  $sessionProfilesTruncated,
  $sessionProfilesUsage,
  $sessionResumeRequest,
  $sessions,
  $sessionsLoading,
  $sessionStartedAt,
  $terminalBackend,
  $turnStartedAt,
  $unreadFinishedSessionIds,
  $workspaceCwdOwner,
  $yoloActive,
  type ActiveSessionStoredIdRotation,
  clearComposerSelectionOwner,
  clearReadBaseline,
  commitWorkspaceCwdForSelectedSession,
  type ComposerModelSource,
  CRON_SECTION_LIMIT,
  getComposerSelectionGeneration,
  getCurrentModelSource,
  getRememberedWorkspaceCwd,
  markAllSessionsRead,
  markComposerSelectionManual,
  markSessionRead,
  MESSAGING_SECTION_LIMIT,
  type NewChatWorkspaceTarget,
  ownerLookupSessionRows,
  type ProfileUsage,
  releaseWorkspaceCwdOwner,
  requestSessionResume,
  type SessionResumeRequest,
  setActiveSessionId,
  setActiveSessionStoredIdRotation,
  setAvailablePersonalities,
  setAwaitingResponse,
  setBusy,
  setComposerSelectionOwner,
  setConnection,
  setContextSuggestions,
  setCronSessions,
  setCurrentBranch,
  setCurrentCwd,
  setCurrentCwdTransient,
  setCurrentFastMode,
  setCurrentModel,
  setCurrentModelSource,
  setCurrentPersonality,
  setCurrentProvider,
  setCurrentReasoningEffort,
  setCurrentServiceTier,
  setCurrentUsage,
  setDefaultReasoningEffort,
  setFreshDraftReady,
  setGatewayState,
  setIntroPersonality,
  setIntroSeed,
  setMessages,
  setMessagingPlatformTotals,
  setMessagingSessions,
  setMessagingTruncated,
  setModelPickerOpen,
  setNewChatWorkspaceTarget,
  setResumeExhaustedSessionId,
  setResumeFailedSessionId,
  setSelectedStoredSessionId,
  setSessionPickerOpen,
  setSessionProfilesTruncated,
  setSessionProfilesUsage,
  setSessions,
  setSessionsLoading,
  setSessionStartedAt,
  setTerminalBackend,
  setTurnStartedAt,
  setWorkspaceCwdOwner,
  setYoloActive,
  workspaceCwdBelongsToSelectedSession
} from './session/atoms'
export {
  applyConfiguredDefaultProjectDir,
  ensureDefaultWorkspaceCwd,
  getConfiguredDefaultProjectDir,
  syncConfiguredDefaultProjectDir,
  workspaceCwdForNewSession
} from './session/default-workspace'
export {
  idsShareLineage,
  lineageAliases,
  resolveComposerSessionKey,
  sessionMatchesStoredId,
  sessionPinId,
  shouldMigrateComposerScope
} from './session/identity'
export {
  carryForwardFailedProfileSessions,
  keepFailedProfileMeta,
  mergeSessionPage,
  touchSessionActivity
} from './session/list-merge'
export {
  _resetLegacyDiscardForTests,
  getRememberedRoute,
  getRememberedSessionId,
  knownSessionOwner,
  knownSessionProfile,
  rememberedSessionProfile,
  sessionBelongsToProfile,
  setRememberedRoute,
  setRememberedSessionId
} from './session/navigation-memory'
export {
  _resetSessionOwnerHintsForTests,
  forgetSessionOwnerHintsForConnection,
  forgetSessionOwnerHintsForSession,
  getSessionOwnerHint,
  getSessionOwnerHints,
  hydrateSessionOwnerHints,
  sessionOwnerRouteFromRow,
  setSessionOwnerHint
} from './session/owner-hints'
