// The session surface's shared reactive state, decomposed (this file stays
// the stable import path with the unchanged public surface):
// - atoms             - the atom bank + scoped-persistence setters + composer selection
// - navigation-memory - remembered last session/route + sync owner knowledge
// - default-workspace - configured default project dir + boot workspace seeding
// - identity          - pins, lineage aliases, composer scope keys
// - list-merge        - sidebar session list merge/carry/refresh
// - owner-hints       - persisted exact owner routes

export {
  $activeSessionId,
  $activeSessionStoredIdRotation,
  $awaitingResponse,
  $availablePersonalities,
  $busy,
  $connection,
  $contextSuggestions,
  $cronSessions,
  $currentBranch,
  $currentCwd,
  $currentFastMode,
  $currentModel,
  $currentModelSource,
  $currentPersonality,
  $currentProvider,
  $currentReasoningEffort,
  $currentServiceTier,
  $currentUsage,
  $defaultReasoningEffort,
  $freshDraftReady,
  $gatewayState,
  $introPersonality,
  $introSeed,
  $lastReadAtBySessionId,
  $lastVisibleMessageIsUser,
  $messages,
  $messagesEmpty,
  $messagingPlatformTotals,
  $messagingSessions,
  $messagingTruncated,
  $modelPickerOpen,
  $newChatWorkspaceTarget,
  $newChatWorkspaceTargetGeneration,
  $resumeExhaustedSessionId,
  $resumeFailedSessionId,
  $selectedStoredSessionId,
  $sessionPickerOpen,
  $sessionProfilesTruncated,
  $sessionProfilesUsage,
  $sessionResumeRequest,
  $sessionStartedAt,
  $sessions,
  $sessionsLoading,
  $terminalBackend,
  $turnStartedAt,
  $unreadFinishedSessionIds,
  $workspaceCwdOwner,
  $yoloActive,
  clearComposerSelectionOwner,
  clearReadBaseline,
  commitWorkspaceCwdForSelectedSession,
  CRON_SECTION_LIMIT,
  getComposerSelectionGeneration,
  getCurrentModelSource,
  getRememberedWorkspaceCwd,
  markAllSessionsRead,
  markComposerSelectionManual,
  markSessionRead,
  MESSAGING_SECTION_LIMIT,
  ownerLookupSessionRows,
  releaseWorkspaceCwdOwner,
  requestSessionResume,
  setActiveSessionId,
  setActiveSessionStoredIdRotation,
  setAwaitingResponse,
  setAvailablePersonalities,
  setBusy,
  setComposerSelectionOwner,
  setConnection,
  setCronSessions,
  setContextSuggestions,
  setCurrentBranch,
  setCurrentCwd,
  setCurrentCwdTransient,
  setCurrentFastMode,
  setCurrentModel,
  setCurrentModelSource,
  setCurrentPersonality,
  setCurrentProvider,
  setCurrentReasoningEffort,
  setCurrentServiceTier,
  setCurrentUsage,
  setDefaultReasoningEffort,
  setFreshDraftReady,
  setGatewayState,
  setIntroPersonality,
  setIntroSeed,
  setMessages,
  setMessagingPlatformTotals,
  setMessagingSessions,
  setMessagingTruncated,
  setModelPickerOpen,
  setNewChatWorkspaceTarget,
  setResumeExhaustedSessionId,
  setResumeFailedSessionId,
  setSelectedStoredSessionId,
  setSessionPickerOpen,
  setSessionProfilesTruncated,
  setSessionProfilesUsage,
  setSessionStartedAt,
  setSessions,
  setSessionsLoading,
  setTerminalBackend,
  setTurnStartedAt,
  setWorkspaceCwdOwner,
  setYoloActive,
  workspaceCwdBelongsToSelectedSession,
  type ActiveSessionStoredIdRotation,
  type ComposerModelSource,
  type NewChatWorkspaceTarget,
  type ProfileUsage,
  type SessionResumeRequest
} from './session/atoms'
export {
  _resetLegacyDiscardForTests,
  getRememberedRoute,
  getRememberedSessionId,
  knownSessionOwner,
  knownSessionProfile,
  rememberedSessionProfile,
  setRememberedRoute,
  setRememberedSessionId,
  sessionBelongsToProfile
} from './session/navigation-memory'
export {
  applyConfiguredDefaultProjectDir,
  ensureDefaultWorkspaceCwd,
  getConfiguredDefaultProjectDir,
  workspaceCwdForNewSession,
  syncConfiguredDefaultProjectDir
} from './session/default-workspace'
export {
  idsShareLineage,
  lineageAliases,
  resolveComposerSessionKey,
  sessionMatchesStoredId,
  sessionPinId,
  shouldMigrateComposerScope
} from './session/identity'
export {
  carryForwardFailedProfileSessions,
  keepFailedProfileMeta,
  mergeSessionPage,
  touchSessionActivity
} from './session/list-merge'
export {
  _resetSessionOwnerHintsForTests,
  forgetSessionOwnerHintsForConnection,
  forgetSessionOwnerHintsForSession,
  getSessionOwnerHint,
  getSessionOwnerHints,
  hydrateSessionOwnerHints,
  setSessionOwnerHint,
  sessionOwnerRouteFromRow
} from './session/owner-hints'
