import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { go, Link } from '../app/router'
import { ExecutionHeader } from '../components/ExecutionHeader'
import { Ref, State } from '../components/Chrome'
import { bindingSlots, executionId, type BindingSlot } from '../data/mock'

export function BindingComposer() {
  const { t } = useTranslation(); const [provider, setProvider] = useState(false); const [selected, setSelected] = useState<string | null>(null); const [resolved, setResolved] = useState<string[]>([]); const [optionalOpen, setOptionalOpen] = useState(false); const [review, setReview] = useState(false)
  const required = bindingSlots.filter((slot) => slot.required), optional = bindingSlots.filter((slot) => !slot.required), requiredCount = required.filter((slot) => resolved.includes(slot.slot)).length, optionalCount = optional.filter((slot) => resolved.includes(slot.slot)).length
  const select = (slot: BindingSlot) => provider && setSelected(slot.slot); const resolve = () => { if (selected && !resolved.includes(selected)) setResolved([...resolved, selected]); setSelected(null) }
  if (review) return <BindingReview resolved={resolved} requiredCount={requiredCount} optionalCount={optionalCount} />
  return <section className="page execution-page"><ExecutionHeader phase="draft" /><div className="composer-layout"><aside className="step-rail"><span>01 {t('bindings.stepOne')}</span><span className={provider ? 'done' : ''}>02 {t('bindings.stepTwo')}</span><span className={requiredCount === required.length ? 'done' : ''}>03 {t('bindings.stepThree')}</span><span>04 {t('bindings.stepFour')}</span></aside><section className="composer"><p className="eyebrow">DRAFT REVISION <Ref>7</Ref></p><h2>{t('bindings.title')}</h2><p>{t('bindings.subtitle')}</p><section className="provider-pick"><h3>{t('bindings.providerPrompt')}</h3>{provider ? <div className="provider-selected"><State tone="terminal">{t('bindings.providerSelected')}</State><strong>Codex ExecutionProvider</strong><Ref>provider.codex.local · v0.7.2</Ref><button className="text-button" onClick={() => { setProvider(false); setResolved([]) }}>{t('bindings.changeProvider')}</button></div> : <><p>{t('bindings.providerUnselected')}</p><button className="provider" onClick={() => setProvider(true)}>{t('bindings.chooseProvider')} <Ref>provider.codex.local</Ref></button></>}</section><ResourceSection title={t('bindings.requiredResources')} slots={required} provider={provider} resolved={resolved} select={select} /><section className="optional-section"><button className="optional-toggle" onClick={() => setOptionalOpen(!optionalOpen)} aria-expanded={optionalOpen}>{optionalOpen ? '−' : '+'} {t('bindings.optionalResources')} <Ref>{optionalCount}/{optional.length}</Ref></button>{optionalOpen && <ResourceSection title="" slots={optional} provider={provider} resolved={resolved} select={select} />}</section>{selected && <SelectorDrawer slot={bindingSlots.find((item) => item.slot === selected)!} resolve={resolve} close={() => setSelected(null)} />}{provider && requiredCount === required.length && <button className="primary review-button" onClick={() => setReview(true)}>{t('bindings.review')} →</button>}</section></div></section>
}
function ResourceSection({ title, slots, provider, resolved, select }: { title: string; slots: BindingSlot[]; provider: boolean; resolved: string[]; select: (slot: BindingSlot) => void }) { const { t } = useTranslation(); return <section className="binding-list"><h3>{title}</h3>{slots.map((slot) => <article key={slot.slot} className={resolved.includes(slot.slot) ? 'binding-row resolved' : 'binding-row'}><div><State>{slot.type}</State><small><Ref>{slot.slot}</Ref></small><p><b>{t('bindings.requested')}</b> <Ref>{slot.requested}</Ref></p></div><div className="arrow">→</div><div><b>{t('bindings.exact')}</b>{resolved.includes(slot.slot) ? <Ref>{slot.exact}</Ref> : <span>{t('bindings.unresolved')}</span>}</div><button className="secondary" disabled={!provider} onClick={() => select(slot)}>{resolved.includes(slot.slot) ? t('bindings.replace') : t(slot.label)}</button>{resolved.includes(slot.slot) && <button className="text-button">{t('bindings.remove')}</button>}</article>)}</section> }
function SelectorDrawer({ slot, resolve, close }: { slot: BindingSlot; resolve: () => void; close: () => void }) { const { t } = useTranslation(); const server = slot.type === 'ServerRef'; return <section className="selector-drawer" aria-live="polite"><p className="eyebrow">{t('bindings.selector')}</p><h3>{t(slot.label)}</h3><p>{server ? t('bindings.requestedServer') : t('errors.choice')}</p><div className="choice-options"><button onClick={resolve}><Ref>{server ? 'ServerRef · ssh-resources / staging-server' : slot.requested}</Ref><small>{t('bindings.resolve')}</small></button><button onClick={close}>{t('common.cancel')}</button></div>{server && <Link className="text-link" to="/integrations/resources">{t('bindings.manageResources')} →</Link>}</section> }
function BindingReview({ resolved, requiredCount, optionalCount }: { resolved: string[]; requiredCount: number; optionalCount: number }) { const { t } = useTranslation(); return <section className="page execution-page"><ExecutionHeader phase="draft" /><div className="composer-layout"><aside className="step-rail"><span className="done">01 {t('bindings.stepOne')}</span><span className="done">02 {t('bindings.stepTwo')}</span><span className="done">03 {t('bindings.stepThree')}</span><span className="current">04 {t('bindings.stepFour')}</span></aside><section className="review-sheet"><p className="eyebrow">DRAFT REVISION <Ref>7</Ref></p><h2>{t('bindings.reviewTitle')}</h2><p>{t('bindings.reviewHint')}</p><div className="count-ledger"><strong>{t('bindings.requiredResources')} <Ref>{requiredCount}/6</Ref></strong><strong>{t('bindings.optionalResources')} <Ref>{optionalCount}/1</Ref></strong></div><div className="review-columns"><b>{t('bindings.requested')}</b><b>{t('bindings.exact')} ({t('executions.frozen')})</b>{bindingSlots.filter((slot) => resolved.includes(slot.slot)).flatMap((slot) => [<Ref key={`${slot.slot}-r`}>{slot.requested}</Ref>, <Ref key={`${slot.slot}-e`}>{slot.exact}</Ref>])}</div><div className="validation"><State tone="terminal">{t('bindings.validation')}</State><strong>{t('bindings.ready')}</strong></div><button className="primary" onClick={() => { sessionStorage.setItem('prototype-phase', 'active'); go(`/executions/${executionId}/activity`) }}>{t('bindings.freeze')} →</button></section></div></section> }
