import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { ExecutionHeader } from '../components/ExecutionHeader'
import { PageTitle, Ref, State } from '../components/Chrome'
import { evidenceResources } from '../data/mock'
import { savedChoice, setPrototypeLanguage, type LanguageChoice } from '../i18n'

export function Evidence() { const { t } = useTranslation(); const [audit, setAudit] = useState<string | null>(null); return <section className="page execution-page"><ExecutionHeader phase="terminal" /><PageTitle eyebrow="证据 / RECONCILIATION" title={t('evidence.title')}><p>{t('evidence.noAllUsed')}</p></PageTitle><section className="evidence-table" aria-label={t('evidence.title')}><header><b>{t('evidence.frozen')}</b><b>{t('evidence.observations')}</b><b>{t('evidence.status')}</b></header>{evidenceResources.map((row) => <article key={row.resource}><div><Ref>{row.resource}</Ref><small>{t('evidence.observer')}：{row.observer}</small></div><div>{row.observations.length ? <ul>{row.observations.map((observation) => <li key={observation}>{observation}</li>)}</ul> : <span>{t('evidence.noObservation')}</span>}<small>{t('evidence.coverage')}：{row.coverage}</small></div><div><State tone={row.result}>{t(`evidence.${row.result}`)}</State><button className="text-button" onClick={() => setAudit(row.audit)}>{t('evidence.audit')} →</button></div></article>)}</section>{audit && <aside className="audit" aria-label={t('evidence.audit')}><button className="text-button" onClick={() => setAudit(null)}>{t('common.close')} ×</button><p className="eyebrow">AUDIT / OBSERVATION <Ref>obs-mcp-19</Ref></p><h2>{audit === 'evidence.auditMcp' ? t('evidence.mismatch') : t('evidence.audit')}</h2><p>{audit === 'evidence.auditMcp' ? t('evidence.auditMismatch') : t(audit)}</p><dl><dt>observer ID</dt><dd><Ref>provider.codex.local</Ref></dd><dt>observer role</dt><dd>self-report</dd><dt>observation kind</dt><dd>projected/read-back</dd><dt>result</dt><dd>{audit === 'evidence.auditMcp' ? 'mismatch / partial' : 'recorded'}</dd><dt>coverage</dt><dd>projected surface only</dd><dt>evidence Ref</dt><dd><Ref>evidence:obs-mcp-19</Ref></dd><dt>observed timestamp</dt><dd><Ref>2026-08-29T10:22:14+08:00</Ref></dd><dt>authority</dt><dd>self-report</dd></dl></aside>}</section> }

export function Integrations() { const { t } = useTranslation(); return <section className="page"><PageTitle eyebrow="LOCAL HOST / CAPABILITIES" title={t('integrations.title')}><p>{t('integrations.hint')}</p></PageTitle><section className="integration-ledger"><article><State tone="terminal">{t('integrations.healthy')}</State><h2>Codex ExecutionProvider</h2><Ref>provider.codex.local · v0.7.2</Ref><p>{t('integrations.available')}</p></article><article><State tone="attention">{t('integrations.degraded')}</State><h2>DeepSeek Harness plugin</h2><Ref>plugin.deepseek-harness</Ref><p>{t('integrations.details')}</p></article></section></section> }

export function Settings() { const { t, i18n } = useTranslation(); const [choice, setChoice] = useState<LanguageChoice>(savedChoice()); const change = (value: LanguageChoice) => { setChoice(value); void setPrototypeLanguage(value) }; return <section className="page"><PageTitle eyebrow="LOCAL PREFERENCES" title={t('settings.title')} /><section className="settings-sheet"><h2>{t('settings.locale')}</h2>{(['system', 'zh', 'en'] as const).map((value) => <label key={value}><input type="radio" name="language" checked={choice === value} onChange={() => change(value)} /> {t(`common.${value === 'zh' ? 'chinese' : value === 'en' ? 'english' : 'system'}`)}</label>)}<p>{t('settings.saved')}</p><p>{t('settings.motion')}</p><Ref>{i18n.language}</Ref></section></section> }
