import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { go, Link } from '../app/router'
import { ExecutionHeader } from '../components/ExecutionHeader'
import { PageTitle, Ref, State } from '../components/Chrome'
import { executionId, workId } from '../data/mock'

const phase = () => (sessionStorage.getItem('prototype-phase') || 'draft') as 'draft' | 'active' | 'terminal' | 'finalizing'
const setPhase = (value: string) => { sessionStorage.setItem('prototype-phase', value); go(`/executions/${executionId}/activity?phase=${value}`) }

export function ExecutionOverview() { const { t } = useTranslation(); const current = phase(); return <section className="page execution-page"><ExecutionHeader phase={current} /><section className="overview-grid"><div><p className="eyebrow">{t('executions.responsibility')}</p><h2>{t('works.e2')}</h2><p>{t('works.openWork')}</p></div><dl><dt>{t('executions.provider')}</dt><dd>Codex ExecutionProvider <Ref>provider.codex.local</Ref></dd><dt>{t('executions.created')}</dt><dd><Ref>2026-08-29T10:14:22+08:00</Ref></dd><dt>{t('executions.nextAction')}</dt><dd>{current === 'draft' ? <Link to={`/executions/${executionId}/binding`}>{t('executions.compose')} →</Link> : <Link to={`/executions/${executionId}/activity`}>{t('executions.observe')} →</Link>}</dd></dl></section></section> }

export function Activity() { const { t } = useTranslation(); const current = phase(); const [confirm, setConfirm] = useState(false); if (current === 'terminal') return <section className="page execution-page"><ExecutionHeader phase="terminal" /><section className="terminal-sheet"><State tone="terminal">{t('common.terminal')}</State><h2>{t('executions.terminalHint')}</h2><Link className="primary" to={`/executions/${executionId}/outputs`}>{t('executions.outputs')} →</Link></section></section>; if (current === 'finalizing') return <section className="page execution-page"><ExecutionHeader phase="finalizing" /><section className="finalizing-sheet"><State tone="attention">{t('executions.finalizing')}</State><h2>{t('executions.finalizingHint')}</h2><ol><li>{t('executions.progressOne')}</li><li>{t('executions.progressTwo')}</li><li>{t('executions.progressThree')}</li></ol><button className="primary" onClick={() => setPhase('terminal')}>{t('executions.observe')} →</button></section></section>; if (current === 'draft') return <section className="page execution-page"><ExecutionHeader phase="draft" /><section className="action-sheet"><State>{t('common.draft')}</State><h2>{t('executions.finishBlocked')}</h2><Link className="primary" to={`/executions/${executionId}/binding`}>{t('executions.compose')} →</Link></section></section>; return <section className="page execution-page"><ExecutionHeader phase="active" /><section className="activity-ledger"><div><State tone="active">● {t('common.active')}</State><h2>Native session <Ref>tmux:%42</Ref></h2><p><Ref>observed: 2026-08-29T10:19:14+08:00</Ref> · freshness: observed</p></div><div className="activity-actions"><button className="secondary">{t('executions.observe')}</button><button className="secondary" onClick={() => document.getElementById('attach')?.showModal()}>{t('executions.attach')}</button><button className="primary" onClick={() => setConfirm(true)}>{t('executions.finish')}</button></div></section><dialog id="attach"><form method="dialog" className="dialog"><h2>{t('executions.attachTitle')}</h2><p>{t('executions.attachHint')}</p><Ref>tmux attach -t deepseek-harness:2.1</Ref><menu><button>{t('common.close')}</button></menu></form></dialog>{confirm && <div className="confirm"><section><h2>{t('executions.finishTitle')}</h2><p>{t('executions.finishHint')}</p><button onClick={() => setConfirm(false)}>{t('common.cancel')}</button><button className="primary" onClick={() => setPhase('finalizing')}>{t('executions.confirmFinish')}</button></section></div>}</section> }

export function Outputs() { const { t } = useTranslation(); const terminal = phase() === 'terminal'; const [picked, setPicked] = useState(false); return <section className="page execution-page"><ExecutionHeader phase={terminal ? 'terminal' : 'draft'} /><PageTitle eyebrow="OUTPUTS / IMMUTABLE REFS" title={t('executions.outputs')}><p>{terminal ? t('executions.terminalHint') : t('executions.finishBlocked')}</p></PageTitle>{terminal ? <><section className="output-row"><State tone="terminal">WorkspaceRef</State><div><strong>DeepSeek Harness isolated workspace</strong><Ref>git:ab71e2f · tree:4c17d</Ref></div><button className={picked ? 'secondary selected-choice' : 'secondary'} onClick={() => setPicked(true)}>{picked ? '✓ ' : ''}{t('works.outputChoice')}</button></section>{picked && <section className="continuation"><p className="eyebrow">NEW EXECUTION / E3</p><h2>{t('works.e3')}</h2><p><Ref>source WorkspaceRef → git:ab71e2f</Ref></p><button className="primary" onClick={() => { sessionStorage.setItem('prototype-e3', 'true'); go(`/works/${workId}`) }}>{t('common.create')}</button></section>}</> : null}</section> }
