import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { go, Link } from '../app/router'
import { PageTitle, Ref, State } from '../components/Chrome'
import { executionId, workId } from '../data/mock'

export function Works() { const { t } = useTranslation(); return <section className="page"><PageTitle eyebrow="WORKS / LOCAL LEDGER" title={t('works.listTitle')}><p>{t('works.listHint')}</p></PageTitle><div className="work-table"><Link to={`/works/${workId}`}><span><State tone="attention">● {t('works.openStatus')}</State><strong>{t('works.openWork')}</strong><small><Ref>{workId}</Ref> · E1, E2</small></span><b>→</b></Link><div><span><State>{t('works.completedStatus')}</State><strong>Credential source rollout review</strong><small><Ref>wrk-credential-rollout</Ref></small></span></div></div></section> }

export function WorkOverview() { const { t } = useTranslation(); const [complete, setComplete] = useState(false); const [reason, setReason] = useState(''); const e3 = sessionStorage.getItem('prototype-e3') === 'true'; if (complete) return <section className="page"><PageTitle eyebrow="工作 / 已完成" title={t('works.openWork')}><State tone="terminal">{t('works.completedStatus')}</State></PageTitle><section className="decision closed"><h2>{t('works.completed')}</h2><p><Ref>{reason}</Ref></p></section></section>; return <section className="page"><header className="objective"><div><p className="eyebrow">工作 / 开放 · <Ref>{workId}</Ref></p><h1>{t('works.openWork')}</h1></div></header><section className="current compact"><p className="eyebrow">{t('works.current')}</p><div><strong>{t('works.e2')}</strong><span>{t('works.e2')}</span><State tone="active">● {t('common.active')}</State><Link to={`/executions/${executionId}/overview`}>{t('common.open')} →</Link></div></section><section className="chronicle"><p className="eyebrow">{t('works.historical')}</p><h2>{t('works.chronicle')}</h2><Chronicle title={t('works.e2')} state={t('common.active')} to={`/executions/${executionId}/overview`} /><Chronicle title={t('works.e1')} state={t('works.historical')} to={`/executions/exe-e1-baseline/outputs`} /><>{e3 && <Chronicle title={t('works.e3')} state={t('common.draft')} to={`/executions/exe-e3-continuation/overview`} />}</></section><section className="decision"><p className="eyebrow">{t('works.decide')}</p><h2>{t('works.decideHint')}</h2><div><button className="primary" onClick={() => go(`/executions/${executionId}/overview`)}>{t('works.createExecution')}</button><Link to={`/executions/exe-e1-baseline/outputs`} className="secondary">{t('works.outputChoice')} <Ref>git:ab71e2f</Ref></Link></div></section><button className="text-button complete-low" onClick={() => document.getElementById('completion')?.showModal()}>{t('common.complete')}</button><dialog id="completion"><form method="dialog" className="dialog"><h2>{t('works.completeTitle')}</h2><p>{t('works.completeHint')}</p><label>{t('works.completeReason')}<textarea value={reason} onChange={(event) => setReason(event.target.value)} /></label><menu><button>{t('common.cancel')}</button><button className="primary" disabled={!reason.trim()} onClick={() => setComplete(true)}>{t('works.completeConfirm')}</button></menu></form></dialog></section> }
function Chronicle({ title, state, to }: { title: string; state: string; to: string }) { const { t } = useTranslation(); return <article><span>2026-08-29</span><div><State>{state}</State><h3>{title}</h3><p>Binding frozen · Codex ExecutionProvider · <Ref>dispatch:ds-82a</Ref></p></div><Link to={to}>{t('common.open')} →</Link></article> }
