import { readdirSync, readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

/**
 * Copy guards for the product surface.
 *
 * Two rules the product owes its users, both cheap to violate by accident and
 * both invisible to behavioral tests:
 *
 *  1. **No bare availability word.** "Unavailable" with nothing after it tells
 *     the user nothing they can act on. Every state names WHAT is missing, so
 *     no locale catalog may carry one of these values verbatim. (Value-level,
 *     not a vocabulary ban: "Not available: the service declares no method for
 *     this yet." passes.)
 *
 *  2. **No product-brand claim under the wrong name.** The product is AgentBox;
 *     `hermes` is a HARNESS FAMILY and keeps its name where it appears as one.
 *     This rule judges the copy this round actually owns (the sections below).
 *     The rest of `composer.*` and `profiles.*` still carries legacy sentences
 *     that name the runtime they describe; that sweep continues under P14-D and
 *     the list above GROWS as each section is converted — a rule that judged
 *     the whole catalog today would be red for reasons nobody is fixing here.
 *
 * The scan reads catalog source on purpose: the catalogs ARE the copy, and a
 * translation that reintroduces a bare word is a defect in that locale.
 */
const I18N_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', 'i18n')
const CATALOGS = ['en.ts', 'zh.ts', 'zh-hant.ts', 'ja.ts', 'ar.ts', 'ru.ts'] as const

/** Exactly these values are forbidden — a state named by nothing else. */
const BARE_WORDS = new Set(['unavailable', 'not available', 'offline', 'not connected', 'n/a', 'na'])

/** The product surface's copy sections. A key inside one of these may not name
 *  the harness family as if it were the product. */
const PRODUCT_SECTIONS = [
  'settings.product',
  'sidebar.agentBox',
  'composer.emptyState',
  'composer.modelSelector',
  'composer.modelSelectorSearch',
  'composer.modelSelectorEmpty',
  'composer.modelSelectorDefault',
  'composer.contextUsage',
  'composer.contextUsageUnknown',
  'composer.serviceUnreachable',
  'composer.workspaceMissing',
  'composer.disabledPlaceholder',
  'assistant.thread.loadingResponse',
  'assistant.thread.loadingSession'
] as const

interface Entry {
  path: string
  value: string
}

/**
 * Key paths from the catalog's own indentation. The catalogs are generated by
 * hand but consistently nested, so indentation is a faithful — and honest —
 * reading of structure: two spaces per level, object keys ending in `{`.
 */
function catalogEntries(source: string): Entry[] {
  const entries: Entry[] = []
  const stack: string[] = []

  for (const rawLine of source.split('\n')) {
    const trimmed = rawLine.trim()

    if (!trimmed || trimmed.startsWith('//') || trimmed.startsWith('/*') || trimmed.startsWith('*')) {
      continue
    }

    // The catalog's own root object is not a key line, so the first keyed
    // level (two spaces) is a section, not the root.
    const depth = Math.max(0, Math.floor((rawLine.length - rawLine.trimStart().length) / 2) - 1)
    const keyMatch = /^([A-Za-z0-9_]+):\s*(.*)$/.exec(trimmed)

    if (!keyMatch) {
      continue
    }

    const [, key, rest] = keyMatch
    stack.length = Math.min(stack.length, depth)
    stack[depth] = key

    if (rest.startsWith('{')) {
      continue
    }

    const stringMatch = /^'((?:[^'\\]|\\.)*)'/.exec(rest) ?? /^\[?\s*'((?:[^'\\]|\\.)*)'/.exec(rest)

    if (stringMatch) {
      entries.push({ path: stack.slice(0, depth + 1).join('.'), value: stringMatch[1] })
    }
  }

  return entries
}

const catalogs = new Map(CATALOGS.map(name => [name, readFileSync(join(I18N_DIR, name), 'utf8')]))

describe('catalog copy guards', () => {
  it('has every locale catalog to judge', () => {
    const present = readdirSync(I18N_DIR).filter(entry => (CATALOGS as readonly string[]).includes(entry))

    expect(present.sort()).toEqual([...CATALOGS].sort())
  })

  it('parses key paths from the catalogs (so the rules below are judging real entries)', () => {
    const composerEntries = catalogEntries(catalogs.get('en.ts') ?? '').filter(entry =>
      entry.path.startsWith('composer.')
    )

    expect(composerEntries.length).toBeGreaterThan(20)
    expect(composerEntries.some(entry => entry.path === 'composer.serviceUnreachable')).toBe(true)
  })

  it('never ships a bare availability word in any locale', () => {
    const offenders: Entry[] = []

    for (const [catalog, source] of catalogs) {
      for (const entry of catalogEntries(source)) {
        if (BARE_WORDS.has(entry.value.trim().toLowerCase())) {
          offenders.push({ path: `${catalog}:${entry.path}`, value: entry.value })
        }
      }
    }

    expect(offenders).toEqual([])
  })

  it('keeps the product surface from claiming a harness family name as its own', () => {
    const offenders: Entry[] = []

    for (const [catalog, source] of catalogs) {
      for (const entry of catalogEntries(source)) {
        const onProductSurface = PRODUCT_SECTIONS.some(
          section => entry.path === section || entry.path.startsWith(`${section}.`)
        )

        // Naming the LEGACY runtime while explaining that a legacy surface is
        // absent is a fact about the old product, not a brand claim about this
        // one — the exception is spelled out here rather than left implicit.
        const explainsLegacyAbsence = /legacy|old runtime|旧版|舊版|従来|القديمة|старой/i.test(entry.value)

        if (onProductSurface && /\bHermes\b/.test(entry.value) && !explainsLegacyAbsence) {
          offenders.push({ path: `${catalog}:${entry.path}`, value: entry.value })
        }
      }
    }

    expect(offenders).toEqual([])
  })
})
