import { readdirSync, readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

/**
 * Copy guards for the product surface.
 *
 * Two rules the product owes its users, both cheap to violate by accident and
 * both invisible to behavioral tests:
 *
 *  1. **No bare availability word.** "Unavailable" with nothing after it tells
 *     the user nothing they can act on. Every state names WHAT is missing, so
 *     no locale catalog may carry one of these values verbatim. (Value-level,
 *     not a vocabulary ban: "Not available: the service declares no method for
 *     this yet." passes.)
 *
 *  2. **No product-brand claim under the wrong name.** The product is AgentBox;
 *     `hermes` is a HARNESS FAMILY and keeps its name where it appears as one.
 *     This rule judges the copy this round actually owns (the sections below).
 *     The rest of `composer.*` and `profiles.*` still carries legacy sentences
 *     that name the runtime they describe; that sweep continues under P14-D and
 *     the list above GROWS as each section is converted — a rule that judged
 *     the whole catalog today would be red for reasons nobody is fixing here.
 *
 * The scan reads catalog source on purpose: the catalogs ARE the copy, and a
 * translation that reintroduces a bare word is a defect in that locale.
 */
const SRC_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const I18N_DIR = resolve(SRC_DIR, 'i18n')
const CATALOGS = ['en.ts', 'zh.ts', 'zh-hant.ts', 'ja.ts', 'ar.ts', 'ru.ts'] as const

/** Exactly these values are forbidden — a state named by nothing else. */
const BARE_WORDS = new Set(['unavailable', 'not available', 'offline', 'not connected', 'n/a', 'na'])

/** The ONLY places a catalog value may still name `Hermes`:
 *
 *  1. A HARNESS FAMILY slot — the family is called `hermes`, and the copy that
 *     names it lives under a key path that says so (`...harness`, `...family`,
 *     or a value that IS the family token).
 *  2. A sentence that explains a LEGACY surface's absence — the old runtime is
 *     a fact about what this product does NOT call, and saying so is honest.
 *
 *  Everything else is a product-brand claim and must read AgentBox. */
const FAMILY_PATH = /harness|family|家族|家系|ファミリー|المجموعة|семейств/i
const LEGACY_ABSENCE = /legacy|old runtime|旧版|舊版|旧线|従来|القديمة|старой/i

interface Entry {
  path: string
  value: string
}

/**
 * Key paths from the catalog's own indentation. The catalogs are generated by
 * hand but consistently nested, so indentation is a faithful — and honest —
 * reading of structure: two spaces per level, object keys ending in `{`.
 */
function catalogEntries(source: string): Entry[] {
  const entries: Entry[] = []
  const stack: string[] = []

  for (const rawLine of source.split('\n')) {
    const trimmed = rawLine.trim()

    if (!trimmed || trimmed.startsWith('//') || trimmed.startsWith('/*') || trimmed.startsWith('*')) {
      continue
    }

    // The catalog's own root object is not a key line, so the first keyed
    // level (two spaces) is a section, not the root.
    const depth = Math.max(0, Math.floor((rawLine.length - rawLine.trimStart().length) / 2) - 1)
    const keyMatch = /^([A-Za-z0-9_]+):\s*(.*)$/.exec(trimmed)

    if (!keyMatch) {
      continue
    }

    const [, key, rest] = keyMatch
    stack.length = Math.min(stack.length, depth)
    stack[depth] = key

    if (rest.startsWith('{')) {
      continue
    }

    const stringMatch = /^'((?:[^'\\]|\\.)*)'/.exec(rest) ?? /^\[?\s*'((?:[^'\\]|\\.)*)'/.exec(rest)

    if (stringMatch) {
      entries.push({ path: stack.slice(0, depth + 1).join('.'), value: stringMatch[1] })
    }
  }

  return entries
}

const catalogs = new Map(CATALOGS.map(name => [name, readFileSync(join(I18N_DIR, name), 'utf8')]))

describe('catalog copy guards', () => {
  it('has every locale catalog to judge', () => {
    const present = readdirSync(I18N_DIR).filter(entry => (CATALOGS as readonly string[]).includes(entry))

    expect(present.sort()).toEqual([...CATALOGS].sort())
  })

  it('parses key paths from the catalogs (so the rules below are judging real entries)', () => {
    const composerEntries = catalogEntries(catalogs.get('en.ts') ?? '').filter(entry =>
      entry.path.startsWith('composer.')
    )

    expect(composerEntries.length).toBeGreaterThan(20)
    expect(composerEntries.some(entry => entry.path === 'composer.serviceUnreachable')).toBe(true)
  })

  it('never ships a bare availability word in any locale', () => {
    const offenders: Entry[] = []

    for (const [catalog, source] of catalogs) {
      for (const entry of catalogEntries(source)) {
        if (BARE_WORDS.has(entry.value.trim().toLowerCase())) {
          offenders.push({ path: `${catalog}:${entry.path}`, value: entry.value })
        }
      }
    }

    expect(offenders).toEqual([])
  })

  it('names the product AgentBox everywhere but the two documented exceptions', () => {
    const offenders: Entry[] = []

    for (const [catalog, source] of catalogs) {
      for (const entry of catalogEntries(source)) {
        if (!/\bHermes\b/.test(entry.value)) {
          continue
        }

        const familySlot = entry.value.trim() === 'Hermes' && FAMILY_PATH.test(entry.path)
        const explainsLegacyAbsence = LEGACY_ABSENCE.test(entry.value)

        if (!familySlot && !explainsLegacyAbsence) {
          offenders.push({ path: `${catalog}:${entry.path}`, value: entry.value })
        }
      }
    }

    expect(offenders).toEqual([])
  })
})

/** Production modules on the product path whose user-facing literals are
 *  judged directly (the rest of the tree is the legacy data plane, and the
 *  order keeps internal identifiers as they are). */
const PRODUCT_SOURCE_FILES = [
  'api/client.ts',
  'application/mcp-oauth.ts',
  'application/session/gateway-event/status.ts',
  'components/assistant-ui/thread/message-reactions.tsx',
  'components/assistant-ui/thread/status.tsx',
  'components/chat/intro.tsx',
  'components/hooks/use-gateway-request.ts',
  'features/runtime/gateway/hooks/use-gateway-boot.ts',
  'lib/desktop-slash-commands.ts'
] as const

const USER_FACING_LITERAL =
  /(?:aria-label|title|placeholder|label|message|description|text)\s*[:=]\s*(?:'|\"|`)([^'\"`]*Hermes[^'\"`]*)(?:'|\"|`)/

describe('source copy guards', () => {
  it('keeps the product path from naming the harness family as the product', () => {
    const offenders: string[] = []

    for (const relative of PRODUCT_SOURCE_FILES) {
      const source = readFileSync(resolve(SRC_DIR, relative), 'utf8')

      for (const [index, line] of source.split('\n').entries()) {
        const trimmed = line.trim()

        if (trimmed.startsWith('//') || trimmed.startsWith('*') || trimmed.startsWith('/*')) {
          continue
        }

        if (/\bHermes\b/.test(line) && userFacing(line)) {
          offenders.push(`${relative}:${index + 1}: ${trimmed.slice(0, 100)}`)
        }
      }
    }

    expect(offenders).toEqual([])
  })
})

/** A line is user-facing when a UI/transport prop carries a Hermes literal —
 *  the same property set the sweep used, kept here so it cannot drift. */
function userFacing(line: string): boolean {
  return USER_FACING_LITERAL.test(line)
}
