import { useState } from "react";
import { api } from "../../api/client";
import { useQuery } from "../../api/query";
import { navigate } from "../../app/router";
import { useTranslation } from "react-i18next";

export function HarnessStudio({ harnessId, profileId }: { harnessId?: string; profileId?: string }) {
  const {t}=useTranslation();
  const hs=useQuery(api.harnesses,[]);
  if(!harnessId) return <div className="wb-page"><header className="wb-title"><p>{t('harnesses.eyebrow')}</p><h1>{t('harnesses.title')}</h1><span>{t('harnesses.hint')}</span></header><section className="wb-ledger">{hs.loading&&<p>{t('harnesses.loadingHarnesses')}</p>}{hs.error&&<p className="wb-error">{t('harnesses.error',{message:hs.error.message})}</p>}{hs.data?.harnesses.map(h=><a key={h.id} href={`#/harnesses/${h.id}`}><div><StatusDot value={h.status}/><h2>{h.display_name}</h2><code>{h.id} · v{h.version}</code></div><b>→</b></a>)}</section></div>;
  if(!profileId) return <HarnessDetail harnessId={harnessId}/>;
  return <ProfileDetail harnessId={harnessId} profileId={profileId}/>;
}
function StatusDot({value}:{value:string}) { return <span className="wb-kicker">{value}</span> }
function HarnessDetail({harnessId}:{harnessId:string}) { const {t}=useTranslation(); const q=useQuery(()=>api.profiles(harnessId),[harnessId]); const [create,setCreate]=useState(false); return <div className="wb-page"><header className="wb-title"><p>HARNESS / {harnessId.toUpperCase()}</p><h1>Codex</h1><span>{t('harnesses.codexHint')}</span></header><section className="wb-panel"><h2>{t('harnesses.profiles')}</h2>{q.loading&&<p>{t('harnesses.loading')}</p>}{q.data?.profiles.map(p=><a className="wb-row" key={p.profile_id} href={`#/harnesses/${harnessId}/profiles/${p.profile_id}`}><span><strong>{p.name}</strong><br/><code>{t('harnesses.revision',{revision:p.revision})} · {p.digest.slice(0,18)}…</code></span><b>→</b></a>)}{!q.loading&&!q.data?.profiles.length&&<p className="wb-empty">{t('harnesses.empty')}</p>}<button className="primary" onClick={()=>setCreate(true)}>{t('harnesses.create')}</button></section>{create&&<ProfileForm harnessId={harnessId} onDone={p=>navigate(`/harnesses/${harnessId}/profiles/${p.profile_id}`)}/>}</div> }
function ProfileDetail({harnessId,profileId}:{harnessId:string;profileId:string}) { const q=useQuery(()=>api.profile(harnessId,profileId),[harnessId,profileId]); const [edit,setEdit]=useState(false); const [preview,setPreview]=useState<any>(); if(q.loading)return <div className="wb-page"><p>Loading profile…</p></div>; if(q.error||!q.data)return <div className="wb-page"><p className="wb-error">Unable to load profile.</p></div>; const p=q.data; return <div className="wb-page"><header className="wb-title"><p>CODEX PROFILE</p><h1>{p.name}</h1><span>ProfileRef is a Binding resource. Saving always creates a new immutable revision.</span></header><section className="wb-panel"><p><strong>Revision {p.revision}</strong> · <code>{p.digest}</code></p><p>CredentialSourceRef is a locator only; credential values are never stored or returned.</p><p>Frozen revision {p.revision} remains unchanged when you save a new revision.</p><div className="wb-actions"><button onClick={()=>setEdit(true)}>Edit</button><button onClick={async()=>setPreview(await api.projectionPreview(harnessId,profileId,p.revision))}>Projection Preview</button><button className="primary" onClick={()=>navigate(`/executions/new?profile=${encodeURIComponent(profileId)}&revision=${p.revision}`)}>Use for new Execution Binding</button></div></section>{preview&&<section className="wb-panel"><h2>Execution-scoped projection</h2><p>Exact ProfileRef: <code>{preview.profile_ref.profile_id} · r{preview.profile_ref.revision} · {preview.profile_ref.digest}</code></p>{preview.files.map((f:any)=><p key={f.path}><code>{f.path}</code> · {f.source} · {f.writable?"writable overlay":"immutable"}</p>)}<p>Environment names: {preview.environment_names.join(", ")||"none"} (values hidden)</p><p>{preview.cleanup_policy}</p></section>}{edit&&<ProfileForm harnessId={harnessId} initial={p} onDone={()=>{setEdit(false);q.reload()}}/>}</div> }
function ProfileForm({harnessId,initial,onDone}:{harnessId:string;initial?:any;onDone:(p:any)=>void}) { const {t}=useTranslation(); const [name,setName]=useState(initial?.name||""); const [model,setModel]=useState(initial?.config?.model||""); const [credential,setCredential]=useState(initial?.credential_source_ref?.native_locator === "codex-login/default" ? "codex-login" : "none"); const [error,setError]=useState(""); return <form className="wb-form" onSubmit={async e=>{e.preventDefault();setError("");const data={name,config:{model,provider:initial?.config?.provider||""},capability_refs:initial?.capability_refs||[],credential_source_ref:credential === "codex-login" ? {provider:"codex",native_locator:"codex-login/default"} : null,session_overlay_policy:{mode:"execution-local"}};try{const v=initial?await api.saveProfile(harnessId,initial.profile_id,data,initial.revision):await api.createProfile(harnessId,data);onDone(v.profile)}catch(x:any){setError(x.message)}}}><label>{t('harnesses.createName')}<input value={name} onChange={e=>setName(e.target.value)} required maxLength={128}/></label><label>{t('harnesses.model')}<input value={model} onChange={e=>setModel(e.target.value)} placeholder={t('harnesses.modelPlaceholder')}/></label><label>{t('harnesses.credentialSource')}<select value={credential} onChange={e=>setCredential(e.target.value)}><option value="none">{t('harnesses.credentialNone')}</option><option value="codex-login">{t('harnesses.credentialChatGPT')}</option></select></label><p>{t('harnesses.credentialHint')}</p><p>{t('harnesses.formHint')}</p>{error&&<p className="wb-error">{error}</p>}<button type="button" onClick={()=>onDone(initial)}>{t('harnesses.cancel')}</button><button className="primary">{initial?t('harnesses.saveRevision'):t('harnesses.createAction')}</button></form> }
