echo "runner=$(type -t fn_run_phase || echo absent)"
echo "worker=$(type -t fn_pure_call || echo absent)"
echo "supervisor=$(type -t cmd_start || echo absent)"
echo "budget=$(type -t fn_sol_reserve || echo present)"
echo "gate=$(type -t fn_validate_phase || echo present)"
echo "handoff=$(type -t fn_build_handoff_prompt || echo present)"
